"""Bayesian T1DM forecasting and recommendation toolkit."""

from .acquisition import (
    AcquisitionError,
    AcquisitionRecord,
    ExportWindow,
    NormalizedWindowResult,
    RawApiArtifact,
    TConnectSyncSourceClient,
    StepLogger,
    TandemCredentials,
    backfill_tandem_exports,
    collect_tandem_exports,
    export_daily_timeline_window,
    generate_export_windows,
    load_local_env_file,
    load_tandem_credentials,
    login_tandem_source,
    normalize_tconnectsync_archive,
    normalize_tconnectsync_payloads,
)
from .evaluate import CalibrationSummary, FoldResult, WalkForwardReport, WalkForwardSplit, calibration_summary, run_walk_forward, walk_forward_splits
from .features import FeatureConfig, FeatureFrame, build_feature_frame
from .health_auto_export import (
    AnalysisReadyHealthDataset,
    HealthAutoExportBundle,
    HealthAutoExportImportResult,
    HealthFeatureScreeningResult,
    ModelDataPreparationResult,
    build_analysis_ready_health_dataset,
    build_prepared_model_dataset,
    build_health_context_frame,
    discover_health_auto_export_bundles,
    discover_health_auto_export_bundle,
    has_apple_health_data,
    import_health_auto_export_batch,
    import_health_auto_export,
    intersect_spans,
    load_health_auto_export_tables,
    load_unified_health_auto_export_tables,
    screen_health_features,
    summarize_apple_health_span,
    summarize_tandem_data_span,
    write_health_screening_report,
    write_model_data_preparation_report,
)
from .ingest import IngestedData, TandemCoverage, build_export_manifest, load_tandem_exports, summarize_coverage, summarize_export_manifest, summarize_tandem_raw_dir, summarize_tandem_raw_source, write_export_manifest
from .insulin import insulin_action_curve, expand_bolus_to_grid
from .model import BayesianGlucoseModel, FitDiagnostics, ModelFit, ScenarioForecast, extract_fit_diagnostics
from .quality import DataQualitySummary, assess_data_quality
from .recommend import Recommendation, RecommendationPolicy, Scenario, build_recommendation_policy, recommend_setting_changes
from .report import build_run_summary, write_json_report, write_markdown_report
from .review import write_coverage_review_html, write_run_review_html, write_therapy_evidence_review_html
from .therapy_research import (
    DEFAULT_SEGMENT_SPEC,
    TherapyInfraValidationResult,
    TherapyResearchResult,
    TherapySegment,
    build_therapy_feature_registry,
    build_therapy_research_frame,
    build_source_report_cards,
    parse_model_list,
    parse_therapy_segments,
    run_therapy_research,
    summarize_overnight_basal_evidence,
    validate_therapy_infra,
    write_therapy_infra_validation_artifacts,
    write_therapy_research_artifacts,
)

__all__ = [
    "BayesianGlucoseModel",
    "AcquisitionError",
    "AcquisitionRecord",
    "AnalysisReadyHealthDataset",
    "CalibrationSummary",
    "FeatureConfig",
    "FeatureFrame",
    "HealthAutoExportBundle",
    "HealthAutoExportImportResult",
    "HealthFeatureScreeningResult",
    "ModelDataPreparationResult",
    "ExportWindow",
    "FitDiagnostics",
    "FoldResult",
    "NormalizedWindowResult",
    "IngestedData",
    "DataQualitySummary",
    "ModelFit",
    "RawApiArtifact",
    "Recommendation",
    "RecommendationPolicy",
    "StepLogger",
    "Scenario",
    "ScenarioForecast",
    "TConnectSyncSourceClient",
    "TandemCoverage",
    "TandemCredentials",
    "TherapyResearchResult",
    "TherapyInfraValidationResult",
    "TherapySegment",
    "WalkForwardSplit",
    "DEFAULT_SEGMENT_SPEC",
    "backfill_tandem_exports",
    "build_analysis_ready_health_dataset",
    "build_prepared_model_dataset",
    "collect_tandem_exports",
    "build_feature_frame",
    "build_health_context_frame",
    "build_export_manifest",
    "build_run_summary",
    "build_therapy_feature_registry",
    "build_therapy_research_frame",
    "build_source_report_cards",
    "export_daily_timeline_window",
    "calibration_summary",
    "extract_fit_diagnostics",
    "generate_export_windows",
    "discover_health_auto_export_bundles",
    "discover_health_auto_export_bundle",
    "expand_bolus_to_grid",
    "build_recommendation_policy",
    "import_health_auto_export_batch",
    "import_health_auto_export",
    "intersect_spans",
    "has_apple_health_data",
    "load_local_env_file",
    "insulin_action_curve",
    "load_tandem_exports",
    "load_tandem_credentials",
    "load_health_auto_export_tables",
    "load_unified_health_auto_export_tables",
    "login_tandem_source",
    "normalize_tconnectsync_archive",
    "normalize_tconnectsync_payloads",
    "parse_model_list",
    "parse_therapy_segments",
    "recommend_setting_changes",
    "run_therapy_research",
    "summarize_overnight_basal_evidence",
    "validate_therapy_infra",
    "assess_data_quality",
    "summarize_coverage",
    "summarize_export_manifest",
    "summarize_tandem_raw_dir",
    "summarize_tandem_raw_source",
    "run_walk_forward",
    "screen_health_features",
    "summarize_apple_health_span",
    "summarize_tandem_data_span",
    "walk_forward_splits",
    "WalkForwardReport",
    "write_coverage_review_html",
    "write_health_screening_report",
    "write_model_data_preparation_report",
    "write_json_report",
    "write_markdown_report",
    "write_therapy_infra_validation_artifacts",
    "write_therapy_research_artifacts",
    "write_therapy_evidence_review_html",
    "write_run_review_html",
    "write_export_manifest",
]
